name: Deploy to EC2 on Merge

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: CI=false npm run build

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > gyb-staging-key.pem
        chmod 600 gyb-staging-key.pem
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        tar -czf browser.tar.gz -C dist .
        scp -i gyb-staging-key.pem browser.tar.gz ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/
        ssh -i gyb-staging-key.pem ec2-user@${{ secrets.EC2_HOST }} 'sudo bash -s' <<'ENDSSH'
        #!/bin/bash
        sudo tar -xzf /home/ec2-user/browser.tar.gz -C /var/www/html
        sudo chown -R ec2-user:nginx /var/www/html
        sudo chmod -R 755 /var/www/html
        rm /home/ec2-user/browser.tar.gz
        sudo nginx -t && sudo systemctl restart nginx
        ENDSSH